openapi: 3.0.0
info:
  title: Banking API
  description: This is a sample API for banking operations
              including features like account management, fund transfers, transaction history, and balance history.
  version: "3.0"
servers:
  - url: http://dev-test.rester.app/sample1
    description: Sample1 server
paths:
  /accounts:
    get:
      summary: Get a list of accounts
      description: Returns a list of accounts owned by the current user.
      operationId: getAccounts
      parameters:
        - name: X-Auth-Token
          in: header  # Header parameter
          required: true
          schema:
            type: string
          description: The authentication token
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new account
      description: Creates a new account for the current user with the given details.
      operationId: createAccount
      parameters:
        - name: X-Auth-Token
          in: header  # Header parameter
          required: true
          schema:
            type: string
          description: The authentication token
      requestBody:  # Request body parameter
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /accounts/{accountId}:
    get:
      summary: Get account details
      description: Returns the details of the account with the given id.
      operationId: getAccount
      parameters:
        - name: accountId
          in: path  # Path parameter
          required: true
          schema:
            type: string
            format: uuid
          description: The id of the account to retrieve
        - name: X-Auth-Token
          in: header  # Header parameter
          required: true
          schema:
            type: string
          description: The authentication token
      responses:
        '200':
          description: Account details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update account details
      description: Updates the details of the account with the given id.
      operationId: updateAccount
      parameters:
        - name: accountId
          in: path  # Path parameter
          required: true
          schema:
            type: string
            format: uuid
          description: The id of the account to update
        - name: X-Auth-Token
          in: header  # Header parameter
          required: true
          schema:
            type: string
          description: The authentication token
      requestBody:  # Request body parameter
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete account
      description: Deletes the account with the given id.
      operationId: deleteAccount
      parameters:
        - name: accountId
          in: path  # Path parameter
          required: true
          schema:
            type: string
            format: uuid
          description: The id of the account to delete
        - name: X-Auth-Token
          in: header  # Header parameter
          required: true
          schema:
            type: string
          description: The authentication token
      responses:
        '204':
          description: Account deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /transfers:
    get:
      summary: Get a list of transfers
      description: Returns a list of transfers made by or received by the current user.
      operationId: getTransfers
      parameters:
        - name: from
          in: query  # Query string parameter
          required: false
          schema:
            type: string
            format: date-time
          description: The start date of the transfer history
        - name: to
          in: query  # Query string parameter
          required: false
          schema:
            type: string
            format: date-time
          description: The end date of the transfer history
        - name: X-Auth-Token
          in: header  # Header parameter
          required: true
          schema:
            type: string
          description: The authentication token
      responses:
        '200':
          description: A list of transfers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new transfer
      description: Creates a new transfer from the current user's account to another account with the given details.
      operationId: createTransfer
      parameters:
        - name: X-Auth-Token
          in: header  # Header parameter
          required: true
          schema:
            type: string
          description: The authentication token
      requestBody:  # Request body parameter
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
      responses:
        '201':
          description: Transfer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /balances:
    get:
      summary: Get a list of balances
      description: Returns a list of balances for the current user's accounts.
      operationId: getBalances
      parameters:
        - name: X-Auth-Token
          in: header  # Header parameter
          required: true
          schema:
            type: string
          description: The authentication token
      responses:
        '200':
          description: A list of balances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Balance'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the account
        name:
          type: string
          description: The name of the account
        type:
          type: string
          enum: [savings, current, credit]
          description: The type of the account
        currency:
          type: string
          description: The currency of the account
        balance:
          type: number
          format: double
          description: The current balance of the account
      required:
        - id
        - name
        - type
        - currency
        - balance
    Transfer:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the transfer
        fromAccountId:
          type: string
          format: uuid
          description: The id of the account from which the transfer is made
        toAccountId:
          type: string
          format: uuid
          description: The id of the account to which the transfer is made
        amount:
          type: number
          format: double
          description: The amount of the transfer
        currency:
          type: string
          description: The currency of the transfer
        date:
          type: string
          format: date-time
          description: The date and time of the transfer
        status:
          type: string
          enum: [pending, completed, failed]
          description: The status of the transfer
      required:
        - id
        - fromAccountId
        - toAccountId
        - amount
        - currency
        - date
        - status
    Balance:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
          description: The id of the account for which the balance is shown
        balance:
          type: number
          format: double
          description: The current balance of the account
        currency:
          type: string
          description: The currency of the account
      required:
        - accountId
        - balance
        - currency
    Error:
      type: object
      properties:
        code:
          type: string
          description: The error code
        message:
          type: string
          description: The error message
      required:
        - code
        - message